name: music_app_2
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: any
  audio_service: ^0.18.10
  flutter_bloc: ^8.1.6
  get_it: ^7.6.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4
  cached_network_image: any
  audio_video_progress_bar: any
  just_audio_background: any
  rxdart: any
  shared_preferences: ^2.3.1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6

  flutter_lints: ^3.0.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true
